version: '3.5'

services:
  calculator:
    build:
      context: .
      dockerfile: Dockerfile
    image: calculator
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    container_name: calcualator_cont
    restart: unless-stopped
    env_file: .env
    ports:
      - "8000:8000"