# Generated by Django 3.2.9 on 2021-11-19 13:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Calculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operand_1', models.FloatField(verbose_name='operand_1')),
                ('operand_2', models.FloatField(verbose_name='operand_2')),
                ('math_operation', models.CharField(max_length=100, verbose_name='math_operation')),
                ('result', models.FloatField(verbose_name='result')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='person')),
            ],
            options={
                'verbose_name': 'Calculation',
                'verbose_name_plural': 'Calculations',
            },
        ),
    ]
